apiVersion: v1
kind: Pod
metadata:
  name: httpd-test-pod
spec:
  containers:
    - name: test-container
      image: registry.access.redhat.com/rhscl/httpd-24-rhel7
      volumeMounts:
      - name: config-volume
        mountPath: /var/www/html
  volumes:
    - name: config-volume
      configMap:
        name: special-httpd-config
  restartPolicy: Never
